### ISSUE TITLE
please update to 1.21 if this is still worked on!

### ISSUE THREAD

**Issue by flattio** [TheSuperGamer20578/Chromatic#38]
### Problem/Use Cases

this is a very interesting mod and adds some use to the keyboard lighting that razer chroma has! if this were to be updated to 1.21 that would be awesome!

### Feature

update to 1.21

**Comment by TheSuperGamer20578** [comment]
Often I find that Chromatic is quite compatible and usually all I have to do is test it and tick the box saying its compatible. I havn't gotten around to testing it with 1.21 yet because I now use Linux and the Linux port is still in Alpha so I have to use a VM to test. Do you get any errors when you try to run it on 1.21? I might try to finally test it later today.

**Comment by flattio** [comment]
> Often I find that Chromatic is quite compatible and usually all I have to do is test it and tick the box saying its compatible. I havn't gotten around to testing it with 1.21 yet because I now use Linux and the Linux port is still in Alpha so I have to use a VM to test. Do you get any errors when you try to run it on 1.21? I might try to finally test it later today.

sure ill send the error i get, it only happens when actually loading a world 
[22:06:02] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.NoSuchFieldError: Class net.minecraft.class_1294 does not have member field 'net.minecraft.class_1291 field_5899'
	at com.TheSuperGamer20578.chromatic.Layouts.applyStatus(Layouts.java:40) ~[Chromatic-1.2.1(1).jar:?]
	at net.minecraft.class_310.handler$zbd000$chromatic$tick(class_310.java:3232) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	
	hope this helps!

**Comment by TheSuperGamer20578** [comment]
Thank you, I will try to have a fix out within the next week
